import nodemailer from "nodemailer";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { email, fileBase64, filename } = await req.json();

    if (!email || !fileBase64) {
      return NextResponse.json({ error: "Email and file are required" }, { status: 400 });
    }

    if (!process.env.GMAIL_USER || !process.env.GMAIL_PASS) {
      return NextResponse.json(
        { error: "SMTP credentials not configured in system (.env.local)" },
        { status: 500 }
      );
    }

    // Configure the mail transport using environment variables
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_PASS, 
      },
    });

    const mailOptions = {
      from: `"TestFlow System" <${process.env.GMAIL_USER}>`,
      to: email,
      subject: "Test Cases Export Report",
      text: "Hello,\n\nPlease find the exported test cases report attached to this email.\n\nGenerated by TestFlow System.",
      attachments: [
        {
          filename: filename || "TestReport.xlsx",
          content: fileBase64,
          encoding: "base64",
        },
      ],
    };

    await transporter.sendMail(mailOptions);

    return NextResponse.json({ success: true });
  } catch (error: any) {
    console.error("Email send error:", error);
    return NextResponse.json({ error: error.message || "Failed to send email" }, { status: 500 });
  }
}
